version: "3.2"
services:
  calc_core:
    image: andviklar/calculator:calc_core
    depends_on:
      - rabbithost
    networks:
      - webnet
  calc_console:
    image: andviklar/calculator:calc_console
    depends_on:
      - rabbithost
    networks:
      - webnet
  rabbithost:
    networks:
      - webnet
    hostname: rabbithost
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbithost"
    tty: true
networks:
  webnet:
    driver: overlay
    attachable: true